### PR TITLE
Fix macos build system for libuv

### PR DESCRIPTION
**Pull request by neuroscr**

### CODE REVIEW

**Comment by michael-loki** [comment]
I'm not sure why this is required. this is the sort of change which is required out-of-build.

**Comment by majestrate** [comment]
@michael-loki was it broken on your osx ?

**Comment by michael-loki** [comment]
Nope. but my `c++`  is in `/usr/local/bin`.

this is the kind of thing which should be solved with a toolchain file (I think).

**Comment by neuroscr** [comment]
> I'm not sure why this is required. 

because macos by default doesn't search /usr/local for the dependencies. This fixes being able to find and link against libuv

>this is the sort of change which is required out-of-build.

what do you mean by that?

> Nope. but my `c++` is in `/usr/local/bin`.

my c++ is in `/usr/bin`

>this is the kind of thing which should be solved with a toolchain file (I think).

I just resolved it how Jeff resolved the FreeBSD implementation, if you don't like the pattern talk to him.

**Comment by majestrate** [comment]
I think the right way is probably a custom cmake toolchain file for your setup.

**Comment by neuroscr** [comment]
Can someone give me an example or pattern to copy?

**Comment by michael-loki** [comment]
I'll make the changes in #668

**Comment by michael-loki** [comment]
@neuroscr see https://github.com/loki-project/loki-network/pull/668/commits/07377b8d5f371eeffe9ce7aa8898c00f33e8574f

and then when you invoke `cmake`, pass in `-DCMAKE_LIBRARY_PATH=/usr/local/lib`

**Pull request closed without merging**
