### PR TITLE
WIP: embedded http client lib for services tunnelled behind HTTPS

### PR DESCRIPTION
**Pull request by despair86**
see #80
- dns over http
- http/2.0+ stuff, push

### CODE REVIEW

**Comment by michael-loki** [comment]
any chance for a C++ API 🙏

**Comment by despair86** [comment]
@michael-loki will consider, but you have to deal with platform-specific symbol decorations yourself!

**Comment by michael-loki** [comment]
something returning `std::future<Response>` plz

**Comment by despair86** [comment]
also, this came out of the lokinet bootstrap stub for windows, which is written in _K&R C_! 😂

**Pull request merged**
