### PR TITLE
Remove cppbackport from vendor dir

### PR DESCRIPTION
**Pull request by michael-loki**
> 6 additions and 5,019 deletions

### CODE REVIEW

**Comment by jagerman** [comment]
Isn't this going to result in compilation problems with non-cutting-edge compilers?

**Comment by majestrate** [comment]
debian stable is okay with it so that's a reasonable cutoff.

**Comment by majestrate** [comment]
we require c++14 features anyways

**Comment by majestrate** [comment]
@jagerman is this acceptable merge given debian stable handles it?

**Comment by neuroscr** [comment]
what about macos and windows?

**Comment by despair86** [comment]
Filesystem TS is a C++17 feature, `CMAKE_CXX_STANDARD` should be bumped up

looks fine to me, seeing as this never worked on windows anyway -rick

**Comment by michael-loki** [comment]
most compilers have been shipping it under `experimental` for a while, so we don't need to bump to 17.

**Pull request merged**
