### PR TITLE
Use travis_wait because builds/linkers are slow

### PR DESCRIPTION
**Pull request by michael-loki**
https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

### CODE REVIEW

**Comment by majestrate** [comment]
looks like it still fails, does adding LTO help?

**Comment by michael-loki** [comment]
I can’t imagine doing more work in the linker would make it faster.

**Comment by majestrate** [comment]
is there a flag we can pass to the linker to make it more verbose?

**Comment by despair86** [comment]
maybe object libraries are starting to look like a bad idea
since the link editor can just search the library index in a static archive faster
instead of studying each individual object closely to find missing symbols, one by one

**Comment by despair86** [comment]
besides, what *was* the original motivation for switching to object libraries over static archives?

**Comment by michael-loki** [comment]
we aren't using object libraries at all? so idk what you mean?

**Pull request merged**
