### PR TITLE
Win32 cleanup

### PR DESCRIPTION
**Pull request by despair86**
remove a ton of ded code from early win32 stuff

### CODE REVIEW

**Comment by despair86** [comment]
also fixes the pybind build: if we're cross-compiling we may not have a python interpreter available for the target machine so don't even build pybind itself if we've already excluded the pybind code on the lokinet side

**Comment by despair86** [comment]
holy hell this sped up windows quite a bit
getting 4 Mbps down, ~1 Mbps up now

**Comment by majestrate** [comment]
i liek the number of deleted lines

**Comment by despair86** [comment]
coming soon: `llarp/win32/wintun.c`

**Comment by KeeJef** [comment]
Can we get this reviewed and merged, this gives a significant perf increase in upload speed for windows which would be good to get in in time for the 0.7.0 push

**Pull request merged**
