### PR TITLE
move old stuff down a notch

### PR DESCRIPTION
**Pull request by despair86**
for 0.8 windows 8.1+ is practically enforced by ci
windows pre-8 can work but can't be automated

### CODE REVIEW

**Comment by majestrate** [comment]
this reminds me that we need to clean up this readme a bit too.

**Review by melyalex — APPROVED** [review]

**Review by melyalex — APPROVED** [review]

**Comment by despair86** [comment]
unlike most documentation-related patches that have formed the bulk of spam requests this month this at least is a good start to document the brave new reality that our build system has morphed into

**Review by majestrate — APPROVED** [review]

**Comment by majestrate** [comment]
this should go into dev branch

**Comment by despair86** [comment]
@majestrate i can't change the target branch but you can

**Pull request merged**
