### PR TITLE
Compiler macros to disbale iOS build breaking things

### PR DESCRIPTION
**Pull request by liilac**
**Don't merge me to the master branch yet, as this will break existing macOS support**

Some compiler macro conditionals that don't build iOS-incompatible headers when `Darwin` is defined.  This covers macOS as well, which will be using the same APIs and will not need the excluded headers.

`vendor/libtuntap-master/tuntap-unix-darwin.c` isn't really needed for Darwin support; I am writing Darwin support directly touching the llarp job queue.

### CODE REVIEW

**Comment by neuroscr** [comment]
https://stackoverflow.com/a/6802945/7697705

has the proper defines to tell the difference between iOS and MacOS

Note: TARGET_OS_MAC is always true on both
so probably want #if (TARGET_OS_IPHONE || TARGET_IPHONE_SIMULATOR)

**Comment by despair86** [comment]
>iphone sim

or, the platform for which the bizarre `i586-macos-ios` target exists 🤔

**Comment by despair86** [comment]
pr is stale, should we close it?

**Comment by liilac** [comment]
Requesting PR be re-opened; will update with suggestion of using the iOS target detection.

Spent an bit over an hour helping onboard a new dedicated iOS developer, @nielsandriesse , who was experiencing this as a blocking issue, and struggled to work out how to resolve it.

Niels was commenting that as an iOS developer, he doesn't have much familiarity with C/C++ codebases, or more traditional cross-compiling, and found the build infrastructure for this (the C/C++ codebase) to be quite difficult to wrap his head around.

Interest in merging this still?

**Pull request closed without merging**
