### PR TITLE
discard unknown fields in introset for future use

### PR DESCRIPTION
**Pull request by majestrate**
this allows us to put more things into introset in the future without breaking compat

### CODE REVIEW

**Comment by majestrate** [comment]
`BEncodeMaybeReadDictEntry` is a nop if the key does not match the value given as a parameter.

**Comment by jagerman** [comment]
> `BEncodeMaybeReadDictEntry` is a nop if the key does not match the value given as a parameter.

Which is going to be a problem for backwards compatibility.  If a future version adds a key `"j"` into the introset then older clients are going to choke when they find `"j"` but were expecting `"k"`.

**Comment by majestrate** [comment]
the function in question is called per key/value in a dict.

**Comment by jagerman** [comment]
Oh, I see.

**Pull request merged**
