### PR TITLE
Win32 scm daemon

### PR DESCRIPTION
**Pull request by despair86**

### CODE REVIEW

**Comment by despair86** [comment]
@majestrate look how cursed it is!

**Comment by majestrate** [comment]
run `contrib/format.sh` please

**Comment by despair86** [comment]
have clang-format 10 send help

**Comment by majestrate** [comment]
does clang-format 10 not work right?

**Comment by despair86** [comment]
coming soon: an update to the daemon startup parameters to keep keys, RCs, and profiles in `$SystemRoot/lokinet` same way the systemd unit starts up in `/var/run/lokinet`

also a cleanup of `daemon/main.cpp` to get rid of 90% of the platform-specific fuzz

**Comment by majestrate** [comment]
looks like clang format 10 does indeed have different rules yet again...

**Pull request merged**
